#helm install --namespace infra elasticsearch elastic/elasticsearch -f ./elasticsearch/values.yaml
#helm install --namespace infra kibana elastic/kibana
---
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx1024m -Xms1024m"
replicas: 1
minimumMasterNodes: 1
# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "1000m"
    memory: "1024M"
  limits:
    cpu: "2000m"
    memory: "2048M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 1000M