info:
  component: ${spring.application.name}

server:
  port: ${PORT:8081}

spring:  
  application:
    name: turbine-service
  rabbitmq:
    host: localhost
    username: user
    password: admin
  #security for actuator and
  security:
    user:
      name: user
      password: password
      role: ACTUATOR

  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      discovery:
        enabled: true

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
#      new feature most enpoints from http layer not allowed
        include: '*'
