info:
  component: ${spring.application.name}

server:
  port: ${PORT:8081}

spring:  
  application:
    name: turbine-service
  rabbitmq:
    host: localhost
    username: guest
    password: admin
  #security for actuator and
  security:
    user:
      name: user
      password: password
      role: ACTUATOR

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    non-secure-port: 8081
    statusPageUrlPath: /actuator/info
    metadata-map:
      management.context-path: /actuator
      management.hystrix: /
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}


management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
#      new feature most enpoints from http layer not allowed
        include: '*'
