apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: {{.Values.global.baseNamespace}}
data:
  logstash.conf: |
    input { rabbitmq { host => "{{.Values.rabbit.host}}:{{.Values.rabbit.port}}" durable => true user => "{{.Values.rabbit.username}}" password => "{{.Values.rabbit.password}}" heartbeat => 30 queue => "elk"} } output { elasticsearch { hosts =>["elasticsearch-master:9200"] index => "micro-%{serviceName}"} }