apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: {{.Values.global.baseNamespace}}
data:
  config.yml: |
    spring:
      application:
        name: {{.Values.name}}
      profiles:
        active: stash
      security:
        user:
          name: {{.Values.username}}
          password: {{.Values.password}}
          roles: {{.Values.role}}
      cloud:
        kubernetes:
          discovery:
            enabled: {{.Values.discoveryEnabled }}
      rabbitmq:
        host: {{.Values.rabbit.host}}
        username: {{.Values.rabbit.username}}
        password: {{.Values.rabbit.password}}
      zipkin:
        enabled: {{.Values.zipkin.enabled}}
      sleuth:
        messaging:
          enabled: {{.Values.sleuth.messaging.enabled}}
          rabbit:
            enabled: {{.Values.sleuth.messaging.enabled}}
      gateway:
        enabled: true
        routes:
          - id: customer-service
            uri: http://customer-service:8080
            predicates:
              - Path=/api/customers/**
            filters:
              - RewritePath=/api/customers/(?<segment>.*), /$\{segment}
          - id: account-service
            uri: http://account-service:8080
            predicates:
              - Path=/api/accounts/**
            filters:
              - RewritePath=/api/accounts/(?<segment>.*), /$\{segment}
    server:
      port: {{.Values.port }}
      servlet:
        context-path: {{.Values.server.path}}
    management:
      endpoints:
        web:
          base-path: /actuator
      endpoint:
        health:
          show-details: {{.Values.actuator.showValues}}
