kind: Service
apiVersion: v1
metadata:
  name: grafana-ext
  namespace: infra
spec:
  type: LoadBalancer
#  change by you cluster or dns name
  externalIPs:
    - 192.168.49.2
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/component: grafana
