global:
  baseNamespace: microservice
  dockerRegistryUrl: localhost:5000
  hostName: microservice-host
name: turbine-service
replicaCount: 1
port: 8080
image:
  repository: turbine-service
username: user
password: password
role: ACTUATOR
discoveryEnabled: true

resources:
  memory: 512Mi
  java:
    opts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=70.0 -XX:+ExitOnOutOfMemoryError"
actuator:
  showValues: ALWAYS
  path: /turbine/actuator

server:
  path: /turbine
rabbit:
  host: rabbit.infra
  port: 5672
  username: user
  password: password
