info:
  component: ${spring.application.name}
server:
  port: ${PORT:3333}

spring:
  application:
    name: customer-service
  security:
    user:
      name: user
      password: password
      roles: ACTUATOR
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
    discovery:
      enabled: true
  profiles:
    active: kubernetes,stash


management:
  endpoints:
    web:
      exposure:
#      new feature most endpoints from http layer not allowed
        include: '*'
      base-path: /actuator
  metrics:
    enable:
      all: true



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000