info:
  component: ${spring.application.name}
server:
  port: ${PORT:3333}

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: admin
    port: 5672
  zipkin:
    compression:
      enabled: true
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
    sender:
      type: rabbit
    encoder: json_v1
  sleuth:
    sampler:
      probability: 1.0
    messaging:
      enabled: true
      rabbit:
        enabled: true
  application:
    name: customer-service
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true


logging:
  config: classpath:logbackrabbit.xml

security:
  user:
    name: user
    password: password


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000