info:
  component: ${spring.application.name}
server:
  port: ${PORT:3333}

spring:
  application:
    name: customer-service
  security:
    user:
      name: user
      password: password
      roles: ACTUATOR

#security for actuator andF

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    health-check-url-path: /actuator/health
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadata-map:
      management.context-path: /actuator
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
#      new feature most endpoints from http layer not allowed
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
        step: 2s
        pushgateway:
          push-rate: 2s
          enabled: true
          grouping-key:
            instance: ${server.address:localhost}:${server.port}
            application: ${spring.application.name}
    enable:
      all: true



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
logging:
  config: