info:
  component: ${spring.application.name}
server:
  port: ${PORT:3333}
feign:
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true
feign-clients:
  account-service:
    url: http://localhost:3334
spring:
  application:
    name: customer-service
  security:
    user:
      name: user
      password: password
      roles: ACTUATOR
  cloud:
    kubernetes:
      reload:
        enabled: false
        mode: polling
        period: 5000
      loadbalancer:
        enabled: false
    discovery:
      enabled: false

  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672


  zipkin:
    compression:
      enabled: true
    base-url: http://localhost:9411
    enabled: true
    service:
      name: ${spring.application.name}
    sender:
      type: web
    encoder: json_v2
  sleuth:
    sampler:
      probability: 1.0
    messaging:
      enabled: true
      rabbit:
        enabled: false
management:
  endpoints:
    web:
      exposure:
#      new feature most end..points from http layer not allowed
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-detail: true
      show-components: always
  metrics:
    enable:
      all: true
