info:
  component: ${spring.application.name}
server:
  port: ${PORT:3333}

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: admin
    port: 5672
  zipkin:
    compression:
      enabled: true
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
    sender:
      type: rabbit
    encoder: json_v1
  sleuth:
    sampler:
      probability: 1.0
    messaging:
      enabled: true
      rabbit:
        enabled: true
  application:
    name: customer-service
logging:
  config: classpath:logbackrabbit.xml

security:
  user:
    name: user
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    statusPageUrlPath: ${management.context-path}/info
    metadata-map:
       management.context-path: /actuator
       user.name: ${security.user.name}
       user.password: ${security.user.password}

ribbon:
  eureka:
    enabled: true

management:
  security:
    enabled: true
    roles: ACTUATOR
  context-path: /actuator
  endpoints:
    web:
      exposure:
#      new feature most enpoints from http layer not allowed
        include: health, httptrace, info, configprops, metrics, env, mappings, sessions, conditions, beans, auditevents
      base-path: /actuator
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000