info:
  component: ${spring.application.name}
server:
  port: ${PORT:3333}

spring:
  application:
    name: customer-service

#security for actuator and
security:
  user:
    name: user
    password: password
    role: ACTUATOR
  basic:
    path: /actuator/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    statusPageUrlPath: ${management.context-path}/info
    metadata-map:
      management.context-path: /actuator
      user.name: ${security.user.name}
      user.password: ${security.user.password}

ribbon:
  eureka:
    enabled: true

management:
  security:
    enabled: true
    roles: ACTUATOR
  context-path: /actuator
  endpoints:
    web:
      exposure:
#      new feature most enpoints from http layer not allowed
        include: health, httptrace, info, configprops, metrics, env, mappings, sessions, conditions, beans, auditevents
      base-path: /actuator
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000