info:
  component: ${spring.application.name}
server:
  port: ${PORT:3331}
feign:
  hystrix:
    enabled: true

spring:
  profiles:
    include: jsonLogs
  application:
    name: customer-service
  security:
    user:
      name: user
      password: password
      roles: ACTUATOR
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
    discovery:
      enabled: false
  zipkin:
    compression:
      enabled: true
    base-url: http://localhost:9411
    enabled: false
    service:
      name: ${spring.application.name}
    sender:
      type: rabbit
    encoder: json_v2
  sleuth:
    sampler:
      probability: 1.0
    messaging:
      enabled: true
      rabbit:
        enabled: false

management:
  endpoints:
    web:
      exposure:
#      new feature most endpoints from http layer not allowed
        include: '*'
      base-path: /actuator
  metrics:
    enable:
      all: true
  endpoint:
    hystrix:
      stream:
        enabled: false

logbook:
  include:
    - /**
  exclude:
    - /actuator/**
  format.style: json
  minimum-status: 400
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
      - login

  write:
   chunk-size: 1000
  strategy: body-only-if-status-at-least
