global:
  baseNamespace: microservice
  dockerRegistryUrl: localhost:5000
  hostName: microservice-host
name: gateway-service
replicaCount: 1
port: 8080
image:
  repository: gateway-service
username: user
password: password
role: ACTUATOR
discoveryEnabled: true

resources:
  memory: 512Mi
  java:
    opts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=70.0 -XX:+ExitOnOutOfMemoryError"
actuator:
  showValues: ALWAYS
  path: /api/actuator
prometheus:
  scrape: true
server:
  path: /api

zipkin:
  enabled: false
  url: zipkin.infra
  port: 9411
sleuth:
  enabled: true
  messaging:
    enabled: false
