global:
  baseNamespace: microservice
  dockerRegistryUrl: localhost:5000
  hostName: microservice-host
name: gateway-service
replicaCount: 1
port: 8080
image:
  repository: gateway-service
username: user
password: password
role: ACTUATOR
discoveryEnabled: true

resources:
  memory: 512Mi
  java:
    opts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=70.0 -XX:+ExitOnOutOfMemoryError"
actuator:
  showValues: ALWAYS
  path: /actuator
prometheus:
  scrape: true
server:
  path: /
rabbit:
  host: rabbit.infra
  port: 5672
  username: user
  password: password
logstash:
  location: logstash.infra:5044
zipkin:
  enabled: true
  url: zipkin.infra
  port: 9411
sleuth:
  enabled: true
  messaging:
    enabled: true
services:
  accountService:
    url: http://account-service
    port: 8080
  customerService:
    url: http://customer-service
    port: 8080
profile: stdout
datasource:
  jdbcUrl: jdbc:postgresql://postgres-postgresql.infra:5432/test_migration
  schema: public