apiVersion: v1
kind: ConfigMap
metadata:
  name: zipkin-config
  namespace: {{.Values.global.baseNamespace}}
data:
  STORAGE_TYPE: elasticsearch
  ES_HOSTS: elasticsearch-master:9200
  RABBIT_URI: 'amqp://{{.Values.rabbit.username}}:{{.Values.rabbit.password}}@{{.Values.rabbit.host}}:{{.Values.rabbit.port}}'
  RABBIT_QUEUE: zipkin
  RABBIT_ADDRESSES: {{.Values.rabbit.host}}
  RABBIT_PASSWORD: {{.Values.rabbit.password}}
  RABBIT_USER: {{.Values.rabbit.username}}