kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.global.baseNamespace}}
  labels:
    app: {{.Values.name}}
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.name}}

  template:
    metadata:
      labels:
        app: {{.Values.name}}
        version: latest
    spec:
      containers:
        - name: {{.Values.name}}
          image: "{{ $.Values.global.dockerRegistryUrl}}/{{.Values.image.repository}}:{{.Chart.AppVersion}}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: zipkin-config
          ports:
            - containerPort: {{.Values.resources.port}}
          resources:
            requests:
              memory: {{ .Values.resources.memory }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst



