kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway-service
  namespace: default
  labels:
    app: gateway-service
    spring-boot: "true"
    user.name: user
    user.password: password
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway-service
        version: latest
    spec:
      containers:
        - name: gateway-service
          image: localhost:5000/gateway-service:latest
          env:
            - name: management.endpoint.health.show-details
              value: ALWAYS
          ports:
            - containerPort: 8765
              hostPort: 8765

          resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler



