info:
  component: gateway
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

zuul:
  routes:
    account:
      path: /account/**
      serviceId: account-service
    customer:
      path: /customer/**
      serviceId: customer-service

ribbon:
  eureka:
    enabled: false

server:
  port: ${PORT:8765}


management:
  endpoints:
    web:

      exposure:
#      new feature most enpoints from http layer not allowed
        include: '*'
#    hystrix
feign:
  hystrix:
    enabled: true
spring:
  cloud:
    kubernetes:
      reload:
        enabled: false
        mode: polling
        period: 5000
    discovery:
      enabled: false
  security:
    user:
      name: user
      password: password
      roles: ACTUATOR
  rabbitmq:
    host: localhost
    username: user
    password: password
  zipkin:
    compression:
      enabled: true
    base-url: http://localhost:9411
    enabled: true
    service:
      name: ${spring.application.name}
    sender:
      type: rabbit
    encoder: json_v1

  sleuth:
    sampler:
      probability: 1.0
    messaging:
      enabled: true
      rabbit:
        enabled: true


