info:
  component: gateway
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

zuul:
  prefix: /api
  routes:
    account:
      path: /account/**
      serviceId: account-service
    customer:
      path: /customer/**
      serviceId: customer-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    metadata-map:
      management.context-path: /actuator
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
    leaseRenewalIntervalInSeconds: 5
    health-check-url-path: /actuator/health
    leaseExpirationDurationInSeconds: 20

server:
  port: ${PORT:8765}

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO


management:
  endpoints:
    web:
      exposure:
#      new feature most enpoints from http layer not allowed
        include: '*'
#    hystrix
feign:
  hystrix:
    enabled: true
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: admin

  security:
    user:
      name: user
      password: password
      roles: ACTUATOR
