info:
  component: gateway
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

ribbon:
  eureka:
    enabled: false
#zuul:
#  routes:
#    account:
#      path: /account/**
#      serviceId: account-service
#    customer:
#      path: /customer/**
#      serviceId: customer-service

server:
  port: ${PORT:8765}


management:
  endpoints:
    web:

      exposure:
#      new feature most enpoints from http layer not allowed
        include: '*'
#    hystrix
feign:
  hystrix:
    enabled: true
spring:
  cloud:
    kubernetes:
      reload:
        enabled: false
        mode: polling
        period: 5000
      discovery:
        enabled: false
    discovery:
      enabled: false
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: false
          lower-case-service-id: false



      routes:
        - id: customer-service
          uri: http://localhost:3331
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<segment>.*), /$\{segment}
        - id: account-service
          uri: http://localhost:3334
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<segment>.*), /$\{segment}
  security:
    user:
      name: user
      password: password
      roles: ACTUATOR
  zipkin:
    compression:
      enabled: true
    base-url: http://localhost:9411
    enabled: false
    service:
      name: ${spring.application.name}
    sender:
      type: web
    encoder: json_v1
  sleuth:
    sampler:
      probability: 1.0
    messaging:
      enabled: true
      rabbit:
        enabled: false

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
