info:
  component: gateway
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
zuul:
  prefix: /api
  routes:
    account:
      path: /account/**
      serviceId: account-service
    customer:
      path: /customer/**
      serviceId: customer-service


ribbon:
  eureka:
    enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    statusPageUrlPath: ${management.context-path}/info
    metadata-map:
       management.context-path: /actuator
       user.name: ${security.user.name}
       user.password: ${security.user.password}

  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    registerWithEureka: true

server:
  port: ${PORT:8765}

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
#  file: gateway.log

#actuator example

management:
  security:
    enabled: true
    roles: ACTUATOR
  endpoints:

    web:
      exposure:
#      new feature most enpoints from http layer not allowed
        include: health, httptrace, info, configprops, metrics, env, mappings, sessions, conditions, beans, auditevents
      base-path: /actuator
# deprecated
  context-path: /actuator
#security for actuator and
security:
  user:
    name: user
    password: password
    role: ACTUATOR
  basic:
    path: /actuator/**

#    hystrix
feign:
  hystrix:
    enabled: true

spring:
  application:
    name: gateway
  rabbitmq:
    host: localhost
    username: guest
    password: admin
  zipkin:
    compression:
      enabled: true
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0






