info:
  component: gateway
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: ${PORT:8765}


management:
  endpoints:
    web:

      exposure:
#      new feature most enpoints from http layer not allowed
        include: '*'
#    hystrix
feign:
  hystrix:
    enabled: true
spring:
  main:
    web-application-type: reactive
  cloud:
    kubernetes:
      reload:
        enabled: false
        mode: polling
        period: 5000
      discovery:
        enabled: false
    discovery:
      enabled: false
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: false
          lower-case-service-id: false
      routes:
        - id: customer-service
          uri: ${CUSTOMER_SERVICE_URL:http://localhost:3333}
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/(?<segment>.*), /$\{segment}
        - id: account-service
          uri: ${ACCOUNT_SERVICE_URL:http://localhost:3334}
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/accounts/(?<segment>.*), /$\{segment}
  security:
    user:
      name: user
      password: password
      roles: ACTUATOR
  zipkin:
    compression:
      enabled: true
    base-url: http://localhost:9411
    enabled: true
    service:
      name: ${spring.application.name}
    sender:
      type: rabbit
    encoder: json_v1

  sleuth:
    sampler:
      probability: 1.0
    messaging:
      enabled: false
      rabbit:
        enabled: false
  application:
    name: gateway

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
