info:
  component: Gateway Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false


zuul:
#  prefix: /api
  routes:
    account:
      path: /account/**
      serviceId: account-service
    customer:
      path: /customer/**
      serviceId: customer-service
    ws-service:
      path: /ws/**
      serviceId: ws-service
      customSensitiveHeaders: true
  ws:
      brokerages:
        ws-service:
          end-points: /ws-example
          brokers:  /topic
          destination-prefixes: /app



hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 50000

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 50000
  ConnectTimeout: 3000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    statusPageUrlPath: ${management.context-path}/info
    metadata-map:
       management.context-path: /actuator
       user.name: ${security.user.name}
       user.password: ${security.user.password}
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    registerWithEureka: true

#actuator security user
      
server:
  port: ${PORT:8765}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
  file: gataway.log

#actuator example
management:
  security:
    enabled: true
    roles: ACTUATOR
  context-path: /actuator
#security for actuator and
security:
  user:
    name: user
    password: password
    role: ACTUATOR
  basic:
    path: /actuator/**

#    hystrix
feign:
  hystrix:
    enabled: true





