apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector-ext
  namespace: infra
spec:
  type: LoadBalancer
  ports:
    - port: 14250
      name: grpc
      protocol: TCP
    - port: 14268
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
