spring:
  application:
    name: eureka-discovery
  security:
    user:
      name: user
      password: password
      roles: ACTUATOR
server:
  port: ${PORT:8761}
    
eureka:  
  instance:
    hostname: localhost
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 5
    leaseExpirationDurationInSeconds: 5
    #    param to send via eureka metadata for actuator
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registerWithEureka: true
    fetchRegistry: true
  server:
    enableSelfPreservation: true
  dashboard:
    enabled: false


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    export:
      graphite:
        enabled: true
        step: 1s


logging:
  file: /tmp/tmp.log
