apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: microservice
spec:
  provider:
    vault:
      #in vault should present microservice kv engine
      server: "http://vault.default:8200"
      path: "microservice/"
      version: "v2"
      auth:
        #should be manually created secret for token
        tokenSecretRef:
          name: vault-token
          key: token