global:
  baseNamespace: infra
  dockerRegistryUrl: docker.elastic.co/logstash/logstash
  hostName: infra-host
name: logstash
replicaCount: 2

resources:
  memory: 256Mi
  port: 5044
  cpu: 200m
