version: "3.2"
services:
  prometheus:
    image: prom/prometheus:v2.15.2
    networks:
      spring_cloud:
        aliases:
          - prometheus
    volumes:
      - ./prometheus-config/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
  pushgateway:
    image: mrapplejuice/pushgateway:0.3.1
    networks:
      spring_cloud:
        aliases:
          - pushgateway
    ports:
      - 9091:9091

  graphana:
    image: grafana/grafana
    networks:
      spring_cloud:
        aliases:
          - graphana
    ports:
      - 3000:3000


networks:
  spring_cloud:
    external:
      name: spring_cloud
