apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
  namespace: {{.Values.global.baseNamespace}}
data:
  config.properties: |
    spring.security.user.name: {{.Values.username}}
    spring.security.user.password: {{.Values.password}}
    spring.security.user.roles: {{.Values.role}}
    spring.profiles.active: stash
    server.port: {{.Values.port }}
    spring.cloud.kubernetes.discovery.enabled: {{.Values.discoveryEnabled }}
    spring.application.name: {{.Values.name}}
    management.endpoints.web.base-path: {{.Values.actuator.path}}
    management.endpoint.health.show-details: {{.Values.actuator.showValues}}
    server.servlet.context-path: {{.Values.server.path}}
    logstash.location: {{.Values.logstash.location}}