
server:
  port: ${PORT:2223}

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: admin
    port: 5672
  zipkin:
    compression:
      enabled: true
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
    sender:
      type: rabbit
    encoder: json_v1
  sleuth:
    sampler:
      probability: 1.0
    messaging:
      enabled: true
      rabbit:
        enabled: true
  application:
    name: account-service
  cloud:
    zookeeper:
      connect-string: localhost:2181

      discovery:
        enabled: true




logging:
  config: classpath:logbackrabbit.xml

info:
  component: ${spring.application.name}

#secure actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

security:
  user:
    name: user
    password: password
    role: ACTUATOR
  basic:
    path: /actuator/**


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
