info:
  component: ${spring.application.name}
server:
  port: ${PORT:3334}

spring:
  application:
    name: account-service
  security:
    user:
      name: user
      password: password
      roles: ACTUATOR

#security for actuator and

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    health-check-url-path: /actuator/health
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadata-map:
      management.context-path: /actuator
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        #      new feature most endpoints from http layer not allowed
        include: '*'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000