info:
  component: ${spring.application.name}

server:
  port: ${PORT:2223}

spring:  
  application:
    name: account-service
#  sleuth configuration
#  zipkin:
#    compression:
#      enabled: true
#
#    sender:
#      type: web
#    service:
#      name: ${spring.application.name}
#    locator:
#      discovery:
#        enabled: true
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true
management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000