
server:
  port: ${PORT:2223}

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: admin
    port: 5672
  zipkin:
    compression:
      enabled: true
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
    sender:
      type: rabbit
    encoder: json_v1
  sleuth:
    sampler:
      probability: 1.0
    messaging:
      enabled: true
      rabbit:
        enabled: true
  application:
    name: account-service
logging:
  config: classpath:logbackrabbit.xml

info:
  component: ${spring.application.name}

#eureka configuration for dashboard also
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    statusPageUrlPath: ${management.context-path}/info
    metadata-map:
      management.context-path: /actuator
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    registerWithEureka: true

ribbon:
  eureka:
    enabled: true


#secure actuator
management:
  security:
    enabled: true
    roles: ACTUATOR
  context-path: /actuator
  endpoints:
    web:
      exposure:
#      new feature most enpoints from http layer not allowed
        include: health, httptrace, info, configprops, metrics, env, mappings, sessions, conditions, beans, auditevents
      base-path: /actuator

security:
  user:
    name: user
    password: password
    role: ACTUATOR
  basic:
    path: /actuator/**


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
