kind: Deployment
apiVersion: apps/v1
metadata:
  name: discovery
  namespace: default
  labels:
    app: discovery
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery-service
          image: localhost:5000/discovery-service:latest
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://discovery:8761/eureka/
            - name: eureka.instance.prefer-ip-address
              value: "true"
            - name: management.endpoint.health.show-details
              value: ALWAYS
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler


