apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: account-secret
  namespace: microservice
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-6"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: account-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_SECURITY_USER_NAME
      remoteRef:
        #for v2 it the same as microservice/data/account-service
        key: account-service
        property: security.username
    - secretKey: SPRING_SECURITY_USER_PASSWORD
      remoteRef:
        key: account-service
        property: security.password
    - secretKey: SPRING_RABBITMQ_USERNAME
      remoteRef:
        key: account-service
        property: rabbit.username
    - secretKey: SPRING_RABBITMQ_PASSWORD
      remoteRef:
        key: account-service
        property: rabbit.password
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: account-service
        property: db.password
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: account-service
        property: db.url
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: account-service
        property: db.username