info:
  component: ${spring.application.name}

server:
  port: ${PORT:3335}
  servlet-path: /

spring:  
  application:
    name: ws-service
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

management:
  security:
    enabled: false

