kind: Deployment
apiVersion: apps/v1
metadata:
  name: account-service
  namespace: default
  labels:
    app: account-service
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: account-service
        version: latest
    spec:
      containers:
        - name: customer-service
          image: localhost:5000/account-service:latest
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://discovery:8761/eureka/
            - name: eureka.instance.prefer-ip-address
              value: "true"
            - name: management.endpoint.health.show-details
              value: ALWAYS
          ports:
            - containerPort: 3333
          resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler



